### ISSUE TITLE
Release > 1.4

### ISSUE THREAD

**Issue by chris-martin** [diagrams/diagrams-pgf#15]
There is not yet any released version containing a Semigroup for Render (5d34ac07bc1f8ea515bbca4773b8bb56f449be9b).

**Comment by byorgey** [comment]
Ah, apologies for the oversight, I think I missed that change and thought I could just do a revision on Hackage for version bounds.  I've released 1.4.1 to Hackage now.

**Comment by chris-martin** [comment]
Thank you!
