### ISSUE TITLE
New font weights

### ISSUE THREAD

**Issue by byorgey** [diagrams/diagrams-pgf#6]
See the latest travis tests, e.g. https://travis-ci.org/diagrams/diagrams-pgf/jobs/135630584 .  `diagrams-lib` has recently added a bunch of new font weights which need to be handled: see https://github.com/diagrams/diagrams-lib/pull/267 .  "Handled" could mean *e.g.* just adding a catch-all case that does nothing.  I'm not sure if there's something better we could do.

**Comment by cchalmers** [comment]
Yeah, I've just ignored other font weights for now. There are ways of dealing with other font weights but I'm not sure the best way to do it. (I think some of them need font packages etc.)

**Comment by byorgey** [comment]
OK, thanks, sounds reasonable.
